def make_json_data():
    alldata = dict()
    alldata['1']=dict(nomor=1, nama="player [1]", posisi="posisi [1]")
    alldata['2']=dict(nomor=2, nama="player [2]", posisi="posisi [2]")
    alldata['3']=dict(nomor=3, nama="player [3]", posisi="posisi [3]")
    alldata['4']=dict(nomor=4, nama="player [4]", posisi="posisi [4]")
    alldata['5']=dict(nomor=5, nama="player [5]", posisi="posisi [5]")
    alldata['6']=dict(nomor=6, nama="player [6]", posisi="posisi [6]")
    alldata['7']=dict(nomor=7, nama="player [7]", posisi="posisi [7]")
    alldata['8']=dict(nomor=8, nama="player [8]", posisi="posisi [8]")
    alldata['9']=dict(nomor=9, nama="player [9]", posisi="posisi [9]")
    alldata['10']=dict(nomor=10, nama="player [10]", posisi="posisi [10]")
    alldata['11']=dict(nomor=11, nama="player [11]", posisi="posisi [11]")
    alldata['12']=dict(nomor=12, nama="player [12]", posisi="posisi [12]")
    alldata['13']=dict(nomor=13, nama="player [13]", posisi="posisi [13]")
    alldata['14']=dict(nomor=14, nama="player [14]", posisi="posisi [14]")
    alldata['15']=dict(nomor=15, nama="player [15]", posisi="posisi [15]")
    alldata['16']=dict(nomor=16, nama="player [16]", posisi="posisi [16]")
    alldata['17']=dict(nomor=17, nama="player [17]", posisi="posisi [17]")
    alldata['18']=dict(nomor=18, nama="player [18]", posisi="posisi [18]")
    alldata['19']=dict(nomor=19, nama="player [19]", posisi="posisi [19]")
    alldata['20']=dict(nomor=20, nama="player [20]", posisi="posisi [20]")
    return alldata